### ISSUE TITLE
Create a dashboard showcasing the status of the KIT system

### ISSUE THREAD

**Issue by Hzaatiti** [Hzaatiti/meg-pipeline#19]
Use case: lab users will need a way to check if all the systems are working properly, or to see if there is any incident or problem

Solution: A dashboard shows the status of the system, users can access the dashboard online and read about incidents and so on.

The research scientist (me) need to put in the dashboard the status of:
- the SQUID sensors (operational or not) we have 208 sensors
- the marker box status that has five coils (each coil has an operational or not status)
These statuses need to be logged with time and displayed in a nice way on the dashboard.

**Comment by Hzaatiti** [comment]
@EmnaTay how about we start by making a simple dashboard in R containing a small table with columns status, system name, and have it displayed on a page in the sphinx documentation?



![Image](https://github.com/hzaatiti-NYU/meg-pipeline/assets/31512533/4fa32ba2-efc9-466f-930e-39565c398bb2)

Ideally we would have a new menu entry, called "Status and Performance Dashboard" displayed as the ones in blue in the picture above, and below it, a page called "KIT-System Status Dashboard", where we would display that simple table in R.

I am not sure how to link R to sphinx documentation, this could be good to investigate at the beginning :)

**Comment by EmnaTay** [comment]
Would you min if I use other tools maybe in addition to R? like Python or Power Bi ?

**Comment by hzaatiti-NYU** [comment]
Of course, anything that seems more suitable we can go with it

**Comment by EmnaTay** [comment]
okay, thank you!

**Comment by Hzaatiti** [comment]
It seems that to integrate PowerBI with readthedocs (the template that we are using for our current website), that we will need to generate .html embed code from PowerBi, however this feature is only available in the PRO tier, (which we can get if really needed) and not the free tier

**Comment by EmnaTay** [comment]
Yes i noticed that the doc's code didn't have a build folder in it so i steered away from html embed code or anything that will require the conversion to html. I will try out the plotly library that you suggested .

**Comment by hzaatiti-NYU** [comment]
I started a little bit here https://meg-pipeline.readthedocs.io/en/latest/1-systems/systems-dashboard.html
So basically there is an html in here https://github.com/hzaatiti-NYU/meg-pipeline/blob/main/docs/source/_static/plotly_dashboard.html

But it is not displayed correctly yet, I added a performance dashboard tree of content (TOC) webpage

**Comment by EmnaTay** [comment]
What kind of changes are you making in the conf.py?
